version: '3'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/weaviate
  data_processing:
    build: ./QAChat/Data_Processing
    volumes:
      - ./get_tokens.py:/get_tokens.py
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/Data_Processing:/QAChat/Data_Processing

  qa_bot:
    build: ./QAChat/QA_Bot
    volumes:
      - ./get_tokens.py:/get_tokens.py
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/QA_Bot:/QAChat/QA_Bot

  slack_bot:
    build: ./QAChat/Slack_Bot
    volumes:
      - ./get_tokens.py:/get_tokens.py
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/Slack_Bot:/QAChat/Slack_Bot