version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    networks:
      - qachat

  data_processing:
    build: ./QAChat/Data_Processing
    depends_on:
      - weaviate
    env_file:
      - tokens_local.env
    volumes:
      - ./torch_data:/root/.cache/torch/
      - ./DummyData:/DummyData
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/Data_Processing:/QAChat/Data_Processing
    entrypoint: ["python", "/QAChat/Data_Processing/main.py", "DUMMY"]
    networks:
      - qachat

  qa_bot:
    build: ./QAChat/QA_Bot
    restart: unless-stopped
    depends_on:
      - weaviate
    volumes:
      - ./huggingface_data:/root/.cache/huggingface/
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/QA_Bot:/QAChat/QA_Bot
    networks:
      - qachat

  slack_bot:
    build: ./QAChat/Slack_Bot
    restart: unless-stopped
    depends_on:
      - qa_bot
    volumes:
      - ./QAChat/Common:/QAChat/Common
      - ./QAChat/Slack_Bot:/QAChat/Slack_Bot
    networks:
      - qachat

networks:
  qachat: